variables:
  TEST: "123"
#  START_DEPLOY_TO_STAGE: "true"
#  START_DEPLOY_TO_PROD: "true"

stages:
  - test
  - build
  - deploy
#  - integration_test

test:
  image: golang:1.17-alpine
  stage: test
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'
  variables:
    min_coverage: 80
    coverage_result: '/total:\s+\(statements\)\s+(\d+.\d+)\%/'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - apk add --update --no-cache git build-base && rm -rf /var/cache/apk/* 
    - go install github.com/go-swagger/go-swagger/cmd/swagger@latest && go install entgo.io/ent/cmd/ent@latest
    - make generate && make test && make coverage

#integration_tests:
#  image: golang:1.17-alpine
#  stage: integration_test
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#    DOCKER_DRIVER: overlay2
#    DOCKER_TLS_CERTDIR: ""
#  services:
#    - name: docker:20-dind
#      alias: docker
#      command: [ "--tls=false", "--mtu=1300" ]
#      entrypoint: [ "dockerd-entrypoint.sh", "--tls=false" ]
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#  script:
#    - apk add --update --no-cache git build-base docker openrc docker-compose && rm -rf /var/cache/apk/*
#    - go install github.com/go-swagger/go-swagger/cmd/swagger@latest && go install entgo.io/ent/cmd/ent@latest
#    - make generate && make integration-test

lint:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:golangci-lint-alpine
  when: manual
  stage: test
  script:
    - '[ -e .golangci.yml ] || cp /golangci/.golangci.yml .'
    - golangci-lint run --out-format tab | tee ./report.txt
  artifacts:
    paths:
      - report.txt
  allow_failure: true

build:
  image: golang:1.17-alpine
  stage: build
  script:
    - apk add --update --no-cache git make && rm -rf /var/cache/apk/* 
    - apk add build-base
    - go install github.com/go-swagger/go-swagger/cmd/swagger@latest && go install entgo.io/ent/cmd/ent@latest
    - make generate
    - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CGO_LDFLAGS="-static" go build -o $CI_PROJECT_DIR/csr $CI_PROJECT_DIR/cmd/swagger/main.go
  artifacts:
    paths:
      - csr
      
deploy_stage:
  image: kroniak/ssh-client
  environment:
    name: staging
  stage: deploy
  rules:
    - if: $START_DEPLOY_TO_STAGE == "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod -R 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp -o "StrictHostKeyChecking=no" -P$SSH_PORT -r ./csr $SSH_USER@$SSH_HOST:~/tmp_csr
    - scp -o "StrictHostKeyChecking=no" -P$SSH_PORT -r ./db $SSH_USER@$SSH_HOST:/var/www/csr/
    - ssh -o "StrictHostKeyChecking=no" -p$SSH_PORT $SSH_USER@$SSH_HOST STAGE_FILE="$STAGE_FILE" 'sudo service csr stop && cp ~/tmp_csr /var/www/csr/server && sudo service csr start'

deploy_to_prod:
  image: kroniak/ssh-client
  stage: deploy
  environment:
    name: production
  rules:
    - if: $START_DEPLOY_TO_PROD == "true"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
  script:
   - mkdir -p ~/.ssh
   - echo "$SSH_PROD_PRIVATE_KEY" > ~/.ssh/id_rsa
   - chmod -R 700 ~/.ssh
   - echo "$SSH_PROD_KNOWN_HOSTS" >> ~/.ssh/known_hosts
   - chmod 644 ~/.ssh/known_hosts
   - mkdir -p ~/go/config && echo $PRODUCTION_FILE
   - cat $PRODUCTION_FILE >> ~/go/config/.env
   - scp -o "StrictHostKeyChecking=no" -P$SSH_PROD_PORT -i ~/.ssh/id_rsa ~/go/config/.env $SSH_PROD_USER@$SSH_PROD_HOST:/go/.env
   - ssh -o "StrictHostKeyChecking=no" -P$SSH_PROD_PORT -i ~/.ssh/id_rsa $SSH_PROD_USER@$SSH_PROD_HOST 'touch /go/stop && sleep 3 && rm /go/stop'
   - sleep 5
   - scp -o "StrictHostKeyChecking=no" -P$SSH_PROD_PORT -i ~/.ssh/id_rsa -r ./csr $SSH_PROD_USER@$SSH_PROD_HOST:/go/csr
   - sleep 5
   - scp -o "StrictHostKeyChecking=no" -P$SSH_PROD_PORT -i ~/.ssh/id_rsa -r ./db $SSH_PROD_USER@$SSH_PROD_HOST:/go/db
   - sleep 5
   - ssh -o "StrictHostKeyChecking=no" -P$SSH_PROD_PORT -i ~/.ssh/id_rsa $SSH_PROD_USER@$SSH_PROD_HOST 'export $(cat /go/.env | xargs)  &&  cd /go && nohup bash -c "./csr >> log.txt 2>&1 &"'
   - sleep 5
   - ssh -o "StrictHostKeyChecking=no" -P$SSH_PROD_PORT -i ~/.ssh/id_rsa $SSH_PROD_USER@$SSH_PROD_HOST 'cat /go/pid && rm ~/go/.env'
   - rm ~/go/config/.env
