version: "2"

linters:
  default: none
  enable:
    - gocritic
    - ineffassign
    - staticcheck
    - unused
  settings:
    gocritic:
      disable-all: true
      enabled-checks:
        - equalFold
        - boolExprSimplify
    staticcheck:
      checks:
        - all
        - -SA1019
        - -SA2002
        - -ST*
        - ST1019
  exclusions:
    generated: lax
