all: false
dir: '{{.InterfaceDir}}'
filename: mocks.go
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: 'mocks'
recursive: false
require-template-schema-exists: true
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/CSR-LC/csr-be/pkg/domain:
    config:
      all: true
      dir: './internal/generated/mocks'
