// Code generated by entc, DO NOT EDIT.

package statuses

const (
	// Label holds the string label denoting the statuses type in the database.
	Label = "statuses"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the statuses in the database.
	Table = "statuses"
)

// Columns holds all SQL columns for statuses fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "statuses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"equipment_statuses",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
