swagger: "2.0"
info:
  version: "0.0.1"
  title: Be
  description: |
    The API provides CSR backend API.

basePath: /api/
schemes: 
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
consumes:
  - application/json
produces:
  - application/json

paths:
  /v1/users:
    post:
      summary: Register a new user.
      tags:
        - Users
      operationId: postUser
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/CreateUserResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /v1/users/me:
    get:
      summary: Get the current user data.
      security:
        - Bearer: []
      tags:
        - Users
      operationId: getCurrentUser
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    patch:
      summary: Edit selected fields of the current user.
      security:
        - Bearer: []
      tags:
        - Users
      operationId: patchUser
      consumes:
        - application/json
      parameters:
        - name: userPatch
          in: body
          description: The patch to apply to the user.
          required: true
          schema:
            $ref: "#/definitions/PatchRequest"
      responses:
        204:
          description: Success
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /equipment/kinds:
    get:
      summary: Get all kinds.
      tags:
        - Kinds
      operationId: GetAllKinds
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ListOfKinds"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: Create a new kind.
      tags:
        - Kinds
      operationId: CreateNewKind
      parameters:
        - name: name
          in: body
          description: Name of a kind
          required: true
          schema:
            $ref: "#/definitions/CreateNewKind"      
      responses:
        201:
          description: Success
          schema:
            $ref: "#/definitions/CreateNewKindResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /equipment/kinds/{kindId}:
    parameters:
      - name: kindId
        in: path
        required: true
        description: kind id
        type: string
    get:
      summary: Get information about the kind of equipment by id.
      tags:
        - Kinds
      operationId: getKindByID
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/GetKindByIDResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete kind of equipment from db by id.
      tags:
        - Kinds
      operationId: deleteKind
      responses:
        201:
          description: kind of equipment successfully deleted from db 
          schema:
            $ref: "#/definitions/DeleteKindResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"            

definitions:
  Error:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        properties:
          correlationId:
            type: string
          message:
            type: string

  PatchRequest:
    type: array
    items:
      $ref: "#/definitions/PatchItem"
  PatchItem:
    type: object
    description: A JSONPatch document as defined by RFC 6902
    required:
      - op
      - path
    properties:
      from:
        description: A string containing a JSON Pointer value
        type: string
      op:
        description: The operation to be performed
        enum:
          - add
          - remove
          - replace
          - move
          - copy
          - test
        type: string
      path:
        description: A JSON-Pointer
        type: string
      value:
        description: The value to be used within the operations
        type: object

  # User
  User:
    type: object
    required:
      - id
      - createTime
    properties:
      id:
        type: string
      createTime:
        type: string
        format: date-time
  CreateUserResponse:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required:
          - id
        properties:
          id:
            type: string
  GetUserResponse:
    type: object
    required:
      - data
    properties:
      data:
        $ref: "#/definitions/User"
        
  # Kind
  Kind:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
  ListOfKinds:
    type: array
    items:
     $ref: "#/definitions/Kind"
  GetKindByIDResponse:
    type: object
    required:
      - data
    properties:
      data:
        $ref: "#/definitions/Kind"
  DeleteKindResponse:
   type: object
   required:
    - data
   properties:
    data:
      $ref: "#/definitions/Kind"
  CreateNewKind:
   type: object  
   required:
    - data
   properties:
    data:
      $ref: "#/definitions/Kind"    
  CreateNewKindResponse:
   type: object  
   required:
    - data
   properties:
    data:
      $ref: "#/definitions/Kind"
    

