swagger: "2.0"
info:
  version: "0.0.1"
  title: Be
  description: |
    The API provides CSR backend API.

basePath: /api/
schemes: 
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
consumes:
  - application/json
produces:
  - application/json

paths:
  /v1/login:
    post:
      description: 'Returns token for authorized User'
      tags:
        - Users
      operationId: Login
      consumes:
        - "application/json"
      parameters:
        - name: 'login'
          in: 'body'
          required: true
          description: 'Login Payload'
          schema:
            $ref: '#/definitions/LoginInfo'
      responses:
        200:
          description: Successful login
          schema:
            $ref: '#/definitions/LoginSuccessResponse'
        404:
          schema:
            type: string
          description: User not found
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /v1/users:
    post:
      summary: Register a new user.
      tags:
        - Users
      operationId: postUser
      parameters:
        - name: data
          in: body
          description: New user data.
          required: true
          schema:
            $ref: "#/definitions/UserRegister"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/CreateUserResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /v1/users/me:
    get:
      summary: Get the current user data.
      security:
        - Bearer: []
      tags:
        - Users
      operationId: getCurrentUser
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    patch:
      summary: Edit selected fields of the current user.
      security:
        - Bearer: []
      tags:
        - Users
      operationId: patchUser
      consumes:
        - application/json
      parameters:
        - name: userPatch
          in: body
          description: The patch to apply to the user.
          required: true
          schema:
            $ref: "#/definitions/PatchRequest"
      responses:
        204:
          description: Success
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /v1/roles:
    get:
      summary: List all roles.
      tags:
        - Roles
      operationId: GetRoles
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ListRoles"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /v1/management/users/{userId}/role:
    parameters:
      - name: userId
        in: path
        required: true
        description: user id
        type: integer
    post:
      security:
       - Bearer: []
      consumes:
        - application/json
      parameters:
        - name: data
          in: body
          description: Role to assign to user.
          required: true
          schema:
            $ref: "#/definitions/AssignRoleToUser"
      summary: Assign role to user
      tags:
        - Users
      operationId: AssignRoleToUser
      responses:
        200:
          description: Role has been assigned to user
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /equipment/statuses:
    post:
      summary: Creating a new status.
      tags:
        - Status
      operationId: postStatus
      parameters:
        - name: name
          in: body
          description: Status Name
          required: true
          schema:
            $ref: "#/definitions/StatusName"
      responses:
        201:
          description: Status has been created
          schema: 
            $ref: "#/definitions/SuccessStatusOperationResponse" 
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    get:
      summary: List all statuses.
      tags:
        - Status
      operationId: GetStatuses
      responses:
        201:
          description: Success
          schema:
            $ref: "#/definitions/ListStatuses"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /equipment/statuses/{statusId}:
    parameters:
      - name: statusId
        in: path
        required: true
        description: status id
        type: string
    get:
      summary: Get status by id
      tags:
        - Status
      operationId: GetStatus
      responses:
        201:
          description: Status has been created
          schema: 
            $ref: "#/definitions/SuccessStatusOperationResponse" 
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete status by id
      tags:
        - Status
      operationId: DeleteStatus
      responses:
        201:
          description: Status has been created
          schema: 
            $ref: "#/definitions/SuccessStatusOperationResponse" 
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"  
  /equipment/kinds:
    get:
      summary: Get all kinds.
      tags:
        - Kinds
      operationId: GetAllKinds
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ListOfKinds"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: Create a new kind.
      tags:
        - Kinds
      operationId: CreateNewKind
      parameters:
        - name: name
          in: body
          description: Name of a kind
          required: true
          schema:
            $ref: "#/definitions/CreateNewKind"      
      responses:
        201:
          description: Success
          schema:
            $ref: "#/definitions/CreateNewKindResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /equipment/kinds/{kindId}:
    parameters:
      - name: kindId
        in: path
        required: true
        description: kind id
        type: string
    get:
      summary: Get information about the kind of equipment by id.
      tags:
        - Kinds
      operationId: getKindByID
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/GetKindByIDResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete kind of equipment from db by id.
      tags:
        - Kinds
      operationId: deleteKind
      responses:
        201:
          description: kind of equipment successfully deleted from db 
          schema:
            $ref: "#/definitions/DeleteKindResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    patch:
      summary: Edit equipment kind by id.
      tags:
        - Kinds
      operationId: PatchKind
      parameters:
        - name: patchTask
          in: body
          required: true
          schema:
            $ref: '#/definitions/PatchTask'
      responses:
        201:
          description: Success
          schema:
           $ref: "#/definitions/PatchKindResponse"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /v1/active_areas:
    get:
      summary: Get all active areas.
      tags:
        - Active_Areas
      operationId: GetAllActiveAreas
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/ListOfActiveAreas"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"            

definitions:
  Error:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        properties:
          correlationId:
            type: string
          message:
            type: string
  PatchTask:
    type: object
    required:
      - data  
    description: Patch task object (adding max reservation time and max reservation units)
    properties:
      data:
        type: object
        properties:
          max_reservation_time:
            type: integer
            description: max reservation time field
          max_reservation_units:
            type: integer
            description: max reservation units field

  PatchRequest:
    type: array
    items:
      $ref: "#/definitions/PatchItem"
  PatchItem:
    type: object
    description: A JSONPatch document as defined by RFC 6902
    required:
      - op
      - path
    properties:
      from:
        description: A string containing a JSON Pointer value
        type: string
      op:
        description: The operation to be performed
        enum:
          - add
          - remove
          - replace
          - move
          - copy
          - test
        type: string
      path:
        description: A JSON-Pointer
        type: string
      value:
        description: The value to be used within the operations
        type: object

  # User
  LoginInfo:
    type: object
    required:
      - login
      - password
    properties:
      login:
        type: string
      password:
        type: string
  LoginSuccessResponse:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required:
          - token
        properties:
          token:
            type: string
  User:
    type: object
    required:
      - id
      - createTime
      - roleId
      - login
    properties:
      id:
        type: integer
      login:
        type: string
      createTime:
        type: string
        format: date-time
      roleId:
        type: integer
  UserRegister:
    type: object
    required:
      - login
      - password
    properties:
      login:
        type: string
        minLength: 3
      password:
        type: string
        minLength: 6
  CreateUserResponse:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required:
          - id
        properties:
          id:
            type: integer
  GetUserResponse:
    type: object
    required:
      - data
    properties:
      data:
        $ref: "#/definitions/User"
  AssignRoleToUser:
    type: object
    required:
      - roleId
    properties:
      roleId:
        type: integer

  #Role
  Role:
    type: object
    required:
      - id
      - name
      - slug
    properties:
      id:
        type: integer
      name:
        type: string
      slug:
        type: string
  ListRoles:
    type: array
    items:
      $ref: "#/definitions/Role"

  #Status
  Status:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
  ListStatuses:
    type: array
    items:
      $ref: "#/definitions/Status"
  SuccessStatusOperationResponse:
    type: object
    required:
      - data 
    properties:
      data:
        $ref: "#/definitions/Status"
  StatusName:          
    type: object
    required: 
      - name
    properties:
      name: 
        type: string
  # Kind
  Kind:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
      max_reservation_time:
        type: integer
      max_reservation_units:
        type: integer
  ListOfKinds:
    type: array
    items:
     $ref: "#/definitions/Kind"
  GetKindByIDResponse:
    type: object
    required:
      - data
    properties:
      data:
        $ref: "#/definitions/Kind"
  DeleteKindResponse:
   type: object
   required:
    - data
   properties:
    data:
      $ref: "#/definitions/Kind"
  CreateNewKind:
   type: object  
   required:
    - data
   properties:
    data:
      $ref: "#/definitions/Kind"    
  CreateNewKindResponse:
   type: object  
   required:
    - data
   properties:
    data:
      $ref: "#/definitions/Kind"
  PatchKindResponse:
   type: object  
   required:
    - data
   properties:
    data:
      $ref: "#/definitions/Kind"

  #Active Areas
  ActiveArea:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
  ListOfActiveAreas:
    type: array
    items:
     $ref: "#/definitions/ActiveArea"  


