swagger: "2.0"
info:
  version: "0.0.1"
  title: Be
  description: |
    The API provides CSR backend API.

basePath: /api/
schemes:
  - http
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
consumes:
  - application/json
produces:
  - application/json

paths:
  /v1/users:
    post:
      summary: Register a new user.
      tags:
        - Users
      operationId: postUser
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/CreateUserResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /v1/users/me:
    get:
      summary: Get the current user data.
      security:
        - Bearer: []
      tags:
        - Users
      operationId: getCurrentUser
      responses:
        200:
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    patch:
      summary: Edit selected fields of the current user.
      security:
        - Bearer: []
      tags:
        - Users
      operationId: patchUser
      consumes:
        - application/json
      parameters:
        - name: userPatch
          in: body
          description: The patch to apply to the user.
          required: true
          schema:
            $ref: "#/definitions/PatchRequest"
      responses:
        204:
          description: Success
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
  /equipment:
    post:
      summary: Register a new equipment
      tags:
        - Equipment
      operationId: CreateNewEquipment
      consumes:
        - application/json
      parameters:
        - name: newEquipment
          in: body
          description: Create a new equipment
          required: true
          schema:
            $ref: "#/definitions/Equipment"
      responses:
        201:
          description: Equipment created
          schema:
            $ref: "#/definitions/EquipmentResponse"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
  /equipment/{equipmentId}:
    parameters:
      - name: equipmentId
        in: path
        required: true
        description: equipment id
        type: string
    get:
      summary: Get equipment by id
      tags:
        - Equipment
      operationId: GetEquipment
      responses:
        201:
          description: Equipment has been found
          schema:
            $ref: "#/definitions/Equipment"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete equipment by id
      tags:
        - Equipment
      operationId: DeleteEquipment
      responses:
        201:
          description: Equipment has been deleted
          schema:
            $ref: "#/definitions/Equipment"
        default:
          description: Unexpected error.
          schema:
            $ref: "#/definitions/Error"




definitions:
  Error:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        properties:
          correlationId:
            type: string
          message:
            type: string

  PatchRequest:
    type: array
    items:
      $ref: "#/definitions/PatchItem"
  PatchItem:
    type: object
    description: A JSONPatch document as defined by RFC 6902
    required:
      - op
      - path
    properties:
      from:
        description: A string containing a JSON Pointer value
        type: string
      op:
        description: The operation to be performed
        enum:
          - add
          - remove
          - replace
          - move
          - copy
          - test
        type: string
      path:
        description: A JSON-Pointer
        type: string
      value:
        description: The value to be used within the operations
        type: object

  # User
  User:
    type: object
    required:
      - id
      - createTime
    properties:
      id:
        type: string
      createTime:
        type: string
        format: date-time
  CreateUserResponse:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        required:
          - id
        properties:
          id:
            type: string
  GetUserResponse:
    type: object
    required:
      - data
    properties:
      data:
        $ref: "#/definitions/User"
  # Equipment
  Equipment:
    type: object
    required:
      - sku
      - name
      - kind
      - status
      - rate_hour
      - rate_day
      - location
      - description
      - photo
    properties:
      sku:
        type: string
        example: "ABC012345678"
      name:
        type: string
        example: "Dog harness 3000"
      kind:
        type: integer
        example: 5
      status:
        type: integer
        example: 1
      rate_hour:
        type: integer
        example: 110
      rate_day:
        type: integer
        example: 950
      location:
        type: integer
        example: 71
      description:
        type: string
        example: "This is a dog harness.\nWARNING: do not put on cats!"
      photo:
        type: string
        example: "https://..."
  EquipmentResponse:
    type: object
    required:
      - id
      - sku
      - name
      - kind
      - status
      - rate_hour
      - rate_day
      - location
      - description
      - photo
    properties:
      id:
        type: string
        example: 2
      sku:
        type: string
        example: "ABC012345678"
      name:
        type: string
        example: "Dog harness 3000"
      kind:
        type: integer
        example: 5
      status:
        type: integer
        example: 1
      rate_hour:
        type: integer
        example: 110
      rate_day:
        type: integer
        example: 950
      location:
        type: integer
        example: 71
      description:
        type: string
        example: "This is a dog harness.\nWARNING: do not put on cats!"
      photo:
        type: string
        example: "https://..."
