// Code generated by entc, DO NOT EDIT.

package locationts

const (
	// Label holds the string label denoting the locationts type in the database.
	Label = "locationts"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the locationts in the database.
	Table = "locationts"
)

// Columns holds all SQL columns for locationts fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
