// Code generated by entc, DO NOT EDIT.

package locations

const (
	// Label holds the string label denoting the locations type in the database.
	Label = "locations"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the locations in the database.
	Table = "locations"
)

// Columns holds all SQL columns for locations fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "locations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"equipment_locations",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
