// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/equipment"
	"github.com/gofrs/uuid"
)

// Equipment is the model entity for the Equipment schema.
type Equipment struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Sku holds the value of the "sku" field.
	Sku string `json:"sku,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind uuid.UUID `json:"kind,omitempty"`
	// Status holds the value of the "status" field.
	Status uuid.UUID `json:"status,omitempty"`
	// RateHour holds the value of the "rate_hour" field.
	RateHour float64 `json:"rate_hour,omitempty"`
	// RateDay holds the value of the "rate_day" field.
	RateDay float64 `json:"rate_day,omitempty"`
	// Location holds the value of the "location" field.
	Location uuid.UUID `json:"location,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Equipment) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case equipment.FieldRateHour, equipment.FieldRateDay:
			values[i] = new(sql.NullFloat64)
		case equipment.FieldSku, equipment.FieldName, equipment.FieldDescription:
			values[i] = new(sql.NullString)
		case equipment.FieldID, equipment.FieldKind, equipment.FieldStatus, equipment.FieldLocation:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Equipment", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Equipment fields.
func (e *Equipment) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case equipment.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				e.ID = *value
			}
		case equipment.FieldSku:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sku", values[i])
			} else if value.Valid {
				e.Sku = value.String
			}
		case equipment.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				e.Name = value.String
			}
		case equipment.FieldKind:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value != nil {
				e.Kind = *value
			}
		case equipment.FieldStatus:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value != nil {
				e.Status = *value
			}
		case equipment.FieldRateHour:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_hour", values[i])
			} else if value.Valid {
				e.RateHour = value.Float64
			}
		case equipment.FieldRateDay:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_day", values[i])
			} else if value.Valid {
				e.RateDay = value.Float64
			}
		case equipment.FieldLocation:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value != nil {
				e.Location = *value
			}
		case equipment.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				e.Description = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Equipment.
// Note that you need to call Equipment.Unwrap() before calling this method if this Equipment
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Equipment) Update() *EquipmentUpdateOne {
	return (&EquipmentClient{config: e.config}).UpdateOne(e)
}

// Unwrap unwraps the Equipment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Equipment) Unwrap() *Equipment {
	tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Equipment is not a transactional entity")
	}
	e.config.driver = tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Equipment) String() string {
	var builder strings.Builder
	builder.WriteString("Equipment(")
	builder.WriteString(fmt.Sprintf("id=%v", e.ID))
	builder.WriteString(", sku=")
	builder.WriteString(e.Sku)
	builder.WriteString(", name=")
	builder.WriteString(e.Name)
	builder.WriteString(", kind=")
	builder.WriteString(fmt.Sprintf("%v", e.Kind))
	builder.WriteString(", status=")
	builder.WriteString(fmt.Sprintf("%v", e.Status))
	builder.WriteString(", rate_hour=")
	builder.WriteString(fmt.Sprintf("%v", e.RateHour))
	builder.WriteString(", rate_day=")
	builder.WriteString(fmt.Sprintf("%v", e.RateDay))
	builder.WriteString(", location=")
	builder.WriteString(fmt.Sprintf("%v", e.Location))
	builder.WriteString(", description=")
	builder.WriteString(e.Description)
	builder.WriteByte(')')
	return builder.String()
}

// EquipmentSlice is a parsable slice of Equipment.
type EquipmentSlice []*Equipment

func (e EquipmentSlice) config(cfg config) {
	for _i := range e {
		e[_i].config = cfg
	}
}
