// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/kinds"
)

// Kinds is the model entity for the Kinds schema.
type Kinds struct {
	config
	// ID of the ent.
	ID              int `json:"id,omitempty"`
	equipment_kinds *int
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Kinds) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case kinds.FieldID:
			values[i] = new(sql.NullInt64)
		case kinds.ForeignKeys[0]: // equipment_kinds
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Kinds", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Kinds fields.
func (k *Kinds) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kinds.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			k.ID = int(value.Int64)
		case kinds.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field equipment_kinds", value)
			} else if value.Valid {
				k.equipment_kinds = new(int)
				*k.equipment_kinds = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Kinds.
// Note that you need to call Kinds.Unwrap() before calling this method if this Kinds
// was returned from a transaction, and the transaction was committed or rolled back.
func (k *Kinds) Update() *KindsUpdateOne {
	return (&KindsClient{config: k.config}).UpdateOne(k)
}

// Unwrap unwraps the Kinds entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (k *Kinds) Unwrap() *Kinds {
	tx, ok := k.config.driver.(*txDriver)
	if !ok {
		panic("ent: Kinds is not a transactional entity")
	}
	k.config.driver = tx.drv
	return k
}

// String implements the fmt.Stringer.
func (k *Kinds) String() string {
	var builder strings.Builder
	builder.WriteString("Kinds(")
	builder.WriteString(fmt.Sprintf("id=%v", k.ID))
	builder.WriteByte(')')
	return builder.String()
}

// KindsSlice is a parsable slice of Kinds.
type KindsSlice []*Kinds

func (k KindsSlice) config(cfg config) {
	for _i := range k {
		k[_i].config = cfg
	}
}
