// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/locationts"
)

// Locationts is the model entity for the Locationts schema.
type Locationts struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Locationts) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case locationts.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Locationts", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Locationts fields.
func (l *Locationts) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case locationts.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Locationts.
// Note that you need to call Locationts.Unwrap() before calling this method if this Locationts
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Locationts) Update() *LocationtsUpdateOne {
	return (&LocationtsClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the Locationts entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Locationts) Unwrap() *Locationts {
	tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Locationts is not a transactional entity")
	}
	l.config.driver = tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Locationts) String() string {
	var builder strings.Builder
	builder.WriteString("Locationts(")
	builder.WriteString(fmt.Sprintf("id=%v", l.ID))
	builder.WriteByte(')')
	return builder.String()
}

// LocationtsSlice is a parsable slice of Locationts.
type LocationtsSlice []*Locationts

func (l LocationtsSlice) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
