// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/locations"
)

// Locations is the model entity for the Locations schema.
type Locations struct {
	config
	// ID of the ent.
	ID                  int `json:"id,omitempty"`
	equipment_locations *int
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Locations) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case locations.FieldID:
			values[i] = new(sql.NullInt64)
		case locations.ForeignKeys[0]: // equipment_locations
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Locations", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Locations fields.
func (l *Locations) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case locations.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int(value.Int64)
		case locations.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field equipment_locations", value)
			} else if value.Valid {
				l.equipment_locations = new(int)
				*l.equipment_locations = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Locations.
// Note that you need to call Locations.Unwrap() before calling this method if this Locations
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Locations) Update() *LocationsUpdateOne {
	return (&LocationsClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the Locations entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Locations) Unwrap() *Locations {
	tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Locations is not a transactional entity")
	}
	l.config.driver = tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Locations) String() string {
	var builder strings.Builder
	builder.WriteString("Locations(")
	builder.WriteString(fmt.Sprintf("id=%v", l.ID))
	builder.WriteByte(')')
	return builder.String()
}

// LocationsSlice is a parsable slice of Locations.
type LocationsSlice []*Locations

func (l LocationsSlice) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
