// Code generated by entc, DO NOT EDIT.

package equipment

const (
	// Label holds the string label denoting the equipment type in the database.
	Label = "equipment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kinds"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "statuses"
	// FieldRateHour holds the string denoting the rate_hour field in the database.
	FieldRateHour = "rate_hour"
	// FieldRateDay holds the string denoting the rate_day field in the database.
	FieldRateDay = "rate_day"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "locations"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// Table holds the table name of the equipment in the database.
	Table = "equipment"
)

// Columns holds all SQL columns for equipment fields.
var Columns = []string{
	FieldID,
	FieldSku,
	FieldName,
	FieldKind,
	FieldStatus,
	FieldRateHour,
	FieldRateDay,
	FieldLocation,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSku holds the default value on creation for the "sku" field.
	DefaultSku string
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
)
