// Code generated by entc, DO NOT EDIT.

package equipment

const (
	// Label holds the string label denoting the equipment type in the database.
	Label = "equipment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kinds"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "statuses"
	// FieldRateHour holds the string denoting the rate_hour field in the database.
	FieldRateHour = "rate_hour"
	// FieldRateDay holds the string denoting the rate_day field in the database.
	FieldRateDay = "rate_day"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "locations"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeKinds holds the string denoting the kinds edge name in mutations.
	EdgeKinds = "kinds"
	// EdgeStatuses holds the string denoting the statuses edge name in mutations.
	EdgeStatuses = "statuses"
	// EdgeLocations holds the string denoting the locations edge name in mutations.
	EdgeLocations = "locations"
	// Table holds the table name of the equipment in the database.
	Table = "equipment"
	// KindsTable is the table that holds the kinds relation/edge.
	KindsTable = "kinds"
	// KindsInverseTable is the table name for the Kinds entity.
	// It exists in this package in order to avoid circular dependency with the "kinds" package.
	KindsInverseTable = "kinds"
	// KindsColumn is the table column denoting the kinds relation/edge.
	KindsColumn = "equipment_kinds"
	// StatusesTable is the table that holds the statuses relation/edge.
	StatusesTable = "statuses"
	// StatusesInverseTable is the table name for the Statuses entity.
	// It exists in this package in order to avoid circular dependency with the "statuses" package.
	StatusesInverseTable = "statuses"
	// StatusesColumn is the table column denoting the statuses relation/edge.
	StatusesColumn = "equipment_statuses"
	// LocationsTable is the table that holds the locations relation/edge.
	LocationsTable = "locations"
	// LocationsInverseTable is the table name for the Locations entity.
	// It exists in this package in order to avoid circular dependency with the "locations" package.
	LocationsInverseTable = "locations"
	// LocationsColumn is the table column denoting the locations relation/edge.
	LocationsColumn = "equipment_locations"
)

// Columns holds all SQL columns for equipment fields.
var Columns = []string{
	FieldID,
	FieldSku,
	FieldName,
	FieldKind,
	FieldStatus,
	FieldRateHour,
	FieldRateDay,
	FieldLocation,
	FieldDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSku holds the default value on creation for the "sku" field.
	DefaultSku string
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
)
