// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Equipment is the predicate function for equipment builders.
type Equipment func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Kinds is the predicate function for kinds builders.
type Kinds func(*sql.Selector)

// Locations is the predicate function for locations builders.
type Locations func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Statuses is the predicate function for statuses builders.
type Statuses func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
